version: '3.3'
services:
  studentlist:
    container_name: studentlist
    networks: 
      - bootcamp13
    # ports:
    #     - '5000'
    volumes:
        - '$PWD/simple_api/student_age.json:/data/student_age.json'
    image: 'studentlist:v1'

  studentlist-ihm:
    environment:
      - USERNAME=toto
      - PASSWORD=python
    container_name: ihm
    networks: 
      - bootcamp13
    ports:
        - '80:80'
    depends_on: 
      - studentlist
    volumes:
        - './website:/var/www/html'
    image: 'php:apache'

  registry:
    container_name: registry
    networks: 
      - registry
    ports:
        - '9500:5000'
    image: registry:2
  
  registry-ui:
    depends_on:
      - registry 
    image: joxit/docker-registry-ui
    ports:
      - "8080:80"
    networks:
      - registry
    environment:
      - REGISTRY_URL="http://registry:5000"
      - REGISTRY_TITLE="BOOTCAMP 13"
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - SINGLE_REGISTRY=true
      - DELETE_IMAGES=true
      - CATALOG_ELEMENTS_LIMIT=10


networks: 
  bootcamp13:
  registry: